
on: [push, pull_request]
name: Build-Docker-Container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: Build the Docker image
       run: docker build --memory=6g . --file Dockerfile
